# Generated by Django 6.0.3 on 2026-03-19 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=50)),
                ('song_genre', models.CharField(choices=[('pop', 'Pop'), ('rock', 'Rock'), ('heavy_metal', 'Heavy_metal'), ('soft_rock', 'Soft_rock'), ('pop_rock', 'Pop_rock'), ('country', 'Country')], max_length=20)),
                ('song_mood', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('romantic', 'Romantic'), ('angry', 'Angry'), ('energetic', 'ENERGETIC'), ('calm', 'Calm')], max_length=20)),
                ('song_base_singer', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('lyrics', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=50)),
                ('shared_link', models.CharField(blank=True, max_length=255)),
                ('sharing_status', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=20)),
                ('generation_status', models.CharField(choices=[('generating', 'Generating'), ('generated', 'Generated'), ('error', 'Error')], max_length=20)),
                ('song_url', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('library', models.ForeignKey(db_column='library_id', on_delete=django.db.models.deletion.CASCADE, related_name='song_library_id', to='backend.library')),
                ('prompt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='song_prompt_id', to='backend.prompt')),
            ],
        ),
        migrations.AddField(
            model_name='library',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library_user_id', to='backend.user'),
        ),
    ]
