# Generated by Django 6.0.3 on 2026-03-19 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library_user_id', to='backend.user'),
        ),
        migrations.AlterField(
            model_name='song',
            name='prompt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='song_prompt_id', to='backend.prompt'),
        ),
    ]
