# Generated by Django 6.0.3 on 2026-03-19 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        ('prompt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=50)),
                ('shared_link', models.CharField(blank=True, max_length=255)),
                ('sharing_status', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=20)),
                ('generation_status', models.CharField(choices=[('generating', 'Generating'), ('generated', 'Generated'), ('error', 'Error')], max_length=20)),
                ('song_url', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('library', models.ForeignKey(db_column='library_id', on_delete=django.db.models.deletion.CASCADE, related_name='song_library_id', to='library.library')),
                ('prompt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='song_prompt_id', to='prompt.prompt')),
            ],
        ),
    ]
